### PR TITLE
Segmentation 

### PR DESCRIPTION
**Pull request by shauray8**
Outputs a CSV file containing all the information @clstaudt had in his transcript data with an addition of the speaker's ID.

### CODE REVIEW

**Comment by clstaudt** [comment]
@shauray8   Thanks, will review.

**Comment by clstaudt** [comment]
Hi @shauray8, thank you for this contribution! I am reviewing the code and trying to run it. Before the merge I would like to request two additions
- additional description around the command line interface. For example, it wasn't entirely clear to me which input is expected for "audio data pre address".

```
╰─ python notebooks/segmentation/segmentations.py                                                                                                                      
usage: segmentations.py [-h] audio data pre address [audio data pre address ...] episode data [episode data ...] transcription data [transcription data ...]
segmentations.py: error: the following arguments are required: audio data pre address, episode data, transcription data

- basic docstrings for the functions in segmentations.py

**Review by clstaudt — CHANGES_REQUESTED** [review]
Hi @shauray8, thank you for this contribution! I am reviewing the code and trying to run it. Before the merge I would like to request two additions
- additional description around the command line interface. For example, it wasn't entirely clear to me which input is expected for "audio data pre address".

```
╰─ python notebooks/segmentation/segmentations.py                                                                                                                      
usage: segmentations.py [-h] audio data pre address [audio data pre address ...] episode data [episode data ...] transcription data [transcription data ...]
segmentations.py: error: the following arguments are required: audio data pre address, episode data, transcription data

- basic docstrings for the functions in segmentations.py

**Comment by shauray8** [comment]
@clstaudt I'll get it done by tomorrow.

**Comment by shauray8** [comment]
@clstaudt I got all the stuff done for all the inputs you can refer to [this](https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fuser-images.githubusercontent.com%2F875194%2F178120874-563cb166-d010-4331-a890-9d6bed1661dc.png)

**Comment by clstaudt** [comment]
@shauray8 Thank you, this is ready to merge

**Pull request merged**
